/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"

bool_t
xdr_files_list (XDR *xdrs, files_list *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->file, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->p_next, sizeof (files_list), (xdrproc_t) xdr_files_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user (XDR *xdrs, user *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ip, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->port, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_users_vector (XDR *xdrs, users_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->users_vector_val, (u_int *) &objp->users_vector_len, ~0,
		sizeof (user), (xdrproc_t) xdr_user))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_add_connected_user_1_argument (XDR *xdrs, add_connected_user_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->in_addr, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->port, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_add_file_1_argument (XDR *xdrs, add_file_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file_name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->description, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_delete_file_1_argument (XDR *xdrs, delete_file_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file_name, ~0))
		 return FALSE;
	return TRUE;
}
