/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "storage.h"


void
storage_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	enum clnt_stat retval_3;
	int result_3;
	char *add_user_1_username;
	enum clnt_stat retval_4;
	int result_4;
	char *delete_user_1_username;
	enum clnt_stat retval_5;
	int result_5;
	char *add_connected_user_1_username;
	char *add_connected_user_1_in_addr;
	char *add_connected_user_1_port;
	enum clnt_stat retval_6;
	int result_6;
	char *delete_connected_user_1_username;
	enum clnt_stat retval_7;
	users_vector result_7;
	enum clnt_stat retval_8;
	int result_8;
	char *add_file_1_username;
	char *add_file_1_file_name;
	char *add_file_1_description;
	enum clnt_stat retval_9;
	int result_9;
	char *delete_file_1_username;
	char *delete_file_1_file_name;
	enum clnt_stat retval_10;
	files_list result_10;
	char *get_files_1_username;
	enum clnt_stat retval_11;
	int result_11;
	char *is_registered_1_username;
	enum clnt_stat retval_12;
	int result_12;
	char *is_connected_1_username;

#ifndef	DEBUG
	clnt = clnt_create (host, STORAGE, STORAGE_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = setup_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = shutdown_1(&result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = add_user_1(add_user_1_username, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = delete_user_1(delete_user_1_username, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = add_connected_user_1(add_connected_user_1_username, add_connected_user_1_in_addr, add_connected_user_1_port, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = delete_connected_user_1(delete_connected_user_1_username, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = get_connected_users_1(&result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_8 = add_file_1(add_file_1_username, add_file_1_file_name, add_file_1_description, &result_8, clnt);
	if (retval_8 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_9 = delete_file_1(delete_file_1_username, delete_file_1_file_name, &result_9, clnt);
	if (retval_9 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_10 = get_files_1(get_files_1_username, &result_10, clnt);
	if (retval_10 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_11 = is_registered_1(is_registered_1_username, &result_11, clnt);
	if (retval_11 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_12 = is_connected_1(is_connected_1_username, &result_12, clnt);
	if (retval_12 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	storage_1 (host);
exit (0);
}
