/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"

bool_t
xdr_file (XDR *xdrs, file *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->filename, 257,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_files_list (XDR *xdrs, files_list *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->files_list_val, (u_int *) &objp->files_list_len, MAX_NUM_OF_FILES,
		sizeof (file), (xdrproc_t) xdr_file))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user (XDR *xdrs, user *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->username, 257,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ip, 16,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->port, 6,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_users_list (XDR *xdrs, users_list *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->users_list_val, (u_int *) &objp->users_list_len, MAX_NUM_OF_USERS,
		sizeof (user), (xdrproc_t) xdr_user))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_add_connected_user_1_argument (XDR *xdrs, add_connected_user_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->in_addr, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->port, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_add_file_1_argument (XDR *xdrs, add_file_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file_name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->description, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_delete_file_1_argument (XDR *xdrs, delete_file_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file_name, ~0))
		 return FALSE;
	return TRUE;
}
